# Generated by Django 5.2.1 on 2025-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProgramEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "program_name",
                    models.CharField(max_length=100, verbose_name="Программа обучения"),
                ),
                (
                    "year_of_admission",
                    models.IntegerField(verbose_name="Год поступления"),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Средний балл (GPA)",
                    ),
                ),
            ],
        ),
    ]
