# Generated by Django 5.2.1 on 2025-05-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classmate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Сокурсник (ФИО)"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="classmates/", verbose_name="Фото"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Менеджер (ФИО)"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="managers/", verbose_name="Фото"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Менеджер ОП",
                "verbose_name_plural": "Менеджеры ОП",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "photo",
                    models.ImageField(upload_to="profiles/", verbose_name="Фото"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("resume", models.TextField(verbose_name="Резюме")),
            ],
        ),
        migrations.CreateModel(
            name="ProgramInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название ОП")),
                ("slug", models.SlugField(unique=True, verbose_name="URL страницы ОП")),
                ("study_content", models.TextField(verbose_name="Что буду изучать")),
                ("learning_outcomes", models.TextField(verbose_name="Чему научусь")),
                ("advantages", models.TextField(verbose_name="Преимущества программы")),
                (
                    "prospects",
                    models.TextField(verbose_name="Перспективы после обучения"),
                ),
            ],
            options={
                "verbose_name": "Описание ОП",
                "verbose_name_plural": "Описания ОП",
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=100, verbose_name="Академический руководитель (ФИО)"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="supervisors/", verbose_name="Фото"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "Академический руководитель",
            },
        ),
    ]
