# Generated by Django 5.2.1 on 2025-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classmate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Сокурсник"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="sitepages/classmates/", verbose_name="Фото"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Менеджер ОП"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="sitepages/managers/", verbose_name="Фото"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
        ),
        migrations.CreateModel(
            name="Me",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "photo",
                    models.ImageField(upload_to="sitepages/me/", verbose_name="Фото"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("resume", models.TextField(verbose_name="Резюме")),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название ОП")),
                ("study_content", models.TextField(verbose_name="Что буду изучать")),
                ("learning_outcomes", models.TextField(verbose_name="Чему научусь")),
                ("advantages", models.TextField(verbose_name="Преимущества")),
                ("prospects", models.TextField(verbose_name="Перспективы")),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=100, verbose_name="Академический руководитель"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="sitepages/supervisors/", verbose_name="Фото"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
            ],
        ),
    ]
